ALTER TABLE `zt_demandpool` ADD `participant` text NOT NULL AFTER `owner`;

ALTER TABLE `zt_story` ADD `fromDemand` mediumint(8) unsigned NOT NULL DEFAULT '0' AFTER `module`;

ALTER TABLE `zt_workflowlayout` ADD `colspan` tinyint(2) default '1' AFTER `vision`;
ALTER TABLE `zt_workflowlayout` ADD `titleWidth` char(10) default 'auto' AFTER `colspan`;
ALTER TABLE `zt_workflowlayout` ADD `titleColspan` tinyint(2) default '1' AFTER `titleWidth`;

ALTER TABLE `zt_workflowaction` ADD `columns` tinyint(2) default '2' AFTER `editedDate`;

alter table `zt_demand` add `businessDesc` text NULL;
alter table `zt_demand` add `businessObjective` text NULL;
alter table `zt_demand` add `businessUnit` text NOT NULL;
alter table `zt_demand` add `project` mediumint(8) unsigned NOT NULL DEFAULT '0';
alter table `zt_demand` add `dept` mediumint(8) unsigned NOT NULL DEFAULT '0';
alter table `zt_demand` add `stage` enum('0','1') NOT NULL DEFAULT '0';

INSERT INTO `zt_workflow`(`parent`, `child`, `type`, `navigator`, `app`, `position`, `module`, `table`, `name`, `titleField`, `contentField`, `flowchart`, `js`, `css`, `order`, `buildin`, `administrator`, `desc`, `version`, `status`, `vision`, `approval`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('', '', 'flow', 'primary', 'demandpool', '', 'demandpool', 'zt_demandpool', '需求池', '', NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, '1.0', 'normal', 'rnd', 'disabled', 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflow`(`parent`, `child`, `type`, `navigator`, `app`, `position`, `module`, `table`, `name`, `titleField`, `contentField`, `flowchart`, `js`, `css`, `order`, `buildin`, `administrator`, `desc`, `version`, `status`, `vision`, `approval`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('', '', 'flow', 'secondary', 'demand', '', 'demand', 'zt_demand', '原始需求', '', NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, '1.0', 'normal', 'rnd', 'disabled', 'admin', '2024-06-18 09:00:00', '', NULL);

INSERT INTO `zt_workflowsql`(`module`, `field`, `action`, `sql`, `vars`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'pool', '', 'select `id`, `name` from `zt_demandpool` where `deleted` = "0"', '[]', 'admin', '2024-06-18 09:00:00', '', NULL);

INSERT INTO `zt_workflowaction`(`module`, `action`, `method`, `name`, `type`, `batchMode`, `extensionType`, `open`, `position`, `layout`, `show`, `order`, `buildin`, `role`, `virtual`, `conditions`, `verifications`, `hooks`, `linkages`, `js`, `css`, `toList`, `blocks`, `desc`, `status`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demandpool', 'browse', 'browse', '需求池列表', 'single', 'different', 'none', 'normal', 'browse', 'normal', 'direct', 0, 1, 'buildin', 0, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'enable', 'rnd', 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowaction`(`module`, `action`, `method`, `name`, `type`, `batchMode`, `extensionType`, `open`, `position`, `layout`, `show`, `order`, `buildin`, `role`, `virtual`, `conditions`, `verifications`, `hooks`, `linkages`, `js`, `css`, `toList`, `blocks`, `desc`, `status`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demandpool', 'create', 'create', '创建需求池', 'single', 'different', 'none', 'normal', 'browseandview', 'normal', 'direct', 0, 1, 'buildin', 0, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'enable', 'rnd', 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowaction`(`module`, `action`, `method`, `name`, `type`, `batchMode`, `extensionType`, `open`, `position`, `layout`, `show`, `order`, `buildin`, `role`, `virtual`, `conditions`, `verifications`, `hooks`, `linkages`, `js`, `css`, `toList`, `blocks`, `desc`, `status`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demandpool', 'edit', 'edit', '编辑需求池', 'single', 'different', 'none', 'normal', 'browseandview', 'normal', 'direct', 0, 1, 'buildin', 0, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'enable', 'rnd', 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowaction`(`module`, `action`, `method`, `name`, `type`, `batchMode`, `extensionType`, `open`, `position`, `layout`, `show`, `order`, `buildin`, `role`, `virtual`, `conditions`, `verifications`, `hooks`, `linkages`, `js`, `css`, `toList`, `blocks`, `desc`, `status`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demandpool', 'delete', 'delete', '删除需求池', 'single', 'different', 'none', 'none', 'browseandview', 'normal', 'direct', 0, 1, 'buildin', 0, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'enable', 'rnd', 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowaction`(`module`, `action`, `method`, `name`, `type`, `batchMode`, `extensionType`, `open`, `position`, `layout`, `show`, `order`, `buildin`, `role`, `virtual`, `conditions`, `verifications`, `hooks`, `linkages`, `js`, `css`, `toList`, `blocks`, `desc`, `status`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demandpool', 'close', 'operate', '关闭需求池', 'single', 'different', 'none', 'modal', 'browseandview', 'normal', 'direct', 0, 1, 'buildin', 0, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'enable', 'rnd', 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowaction`(`module`, `action`, `method`, `name`, `type`, `batchMode`, `extensionType`, `open`, `position`, `layout`, `show`, `order`, `buildin`, `role`, `virtual`, `conditions`, `verifications`, `hooks`, `linkages`, `js`, `css`, `toList`, `blocks`, `desc`, `status`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demandpool', 'view', 'view', '需求池概况', 'single', 'different', 'none', 'normal', 'browse', 'side', 'direct', 0, 1, 'buildin', 0, '', '', '', '', '', '', '', '', '', 'enable', 'rnd', 'admin', '2024-06-18 09:00:00', '', null);
INSERT INTO `zt_workflowaction`(`module`, `action`, `method`, `name`, `type`, `batchMode`, `extensionType`, `open`, `position`, `layout`, `show`, `order`, `buildin`, `role`, `virtual`, `conditions`, `verifications`, `hooks`, `linkages`, `js`, `css`, `toList`, `blocks`, `desc`, `status`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demandpool', 'track', 'track', '需求池矩阵', 'single', 'different', 'none', 'normal', 'browse', 'side', 'direct', 0, 1, 'buildin', 0, '', '', '', '', '', '', '', '', '', 'enable', 'rnd', 'admin', '2024-06-18 09:00:00', '', null);
INSERT INTO `zt_workflowaction`(`module`, `action`, `method`, `name`, `type`, `batchMode`, `extensionType`, `open`, `position`, `layout`, `show`, `order`, `buildin`, `role`, `virtual`, `conditions`, `verifications`, `hooks`, `linkages`, `js`, `css`, `toList`, `blocks`, `desc`, `status`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'browse', 'browse', '原始需求列表', 'single', 'different', 'none', 'normal', 'browse', 'normal', 'direct', 0, 1, 'buildin', 0, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'enable', 'rnd', 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowaction`(`module`, `action`, `method`, `name`, `type`, `batchMode`, `extensionType`, `open`, `position`, `layout`, `show`, `order`, `buildin`, `role`, `virtual`, `conditions`, `verifications`, `hooks`, `linkages`, `js`, `css`, `toList`, `blocks`, `desc`, `status`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'create', 'create', '提交原始需求', 'single', 'different', 'extend', 'normal', 'browseandview', 'normal', 'direct', 0, 1, 'buildin', 0, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'enable', 'rnd', 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowaction`(`module`, `action`, `method`, `name`, `type`, `batchMode`, `extensionType`, `open`, `position`, `layout`, `show`, `order`, `buildin`, `role`, `virtual`, `conditions`, `verifications`, `hooks`, `linkages`, `js`, `css`, `toList`, `blocks`, `desc`, `status`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'batchcreate', 'batchcreate', '批量提交原始需求', 'batch', 'different', 'extend', 'normal', 'browseandview', 'normal', 'direct', 0, 1, 'buildin', 0, '', NULL, '', '', NULL, NULL, '', NULL, '', 'enable', 'rnd', 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowaction`(`module`, `action`, `method`, `name`, `type`, `batchMode`, `extensionType`, `open`, `position`, `layout`, `show`, `order`, `buildin`, `role`, `virtual`, `conditions`, `verifications`, `hooks`, `linkages`, `js`, `css`, `toList`, `blocks`, `desc`, `status`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'edit', 'edit', '编辑原始需求', 'single', 'different', 'extend', 'normal', 'browseandview', 'normal', 'direct', 0, 1, 'buildin', 0, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'enable', 'rnd', 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowaction`(`module`, `action`, `method`, `name`, `type`, `batchMode`, `extensionType`, `open`, `position`, `layout`, `show`, `order`, `buildin`, `role`, `virtual`, `conditions`, `verifications`, `hooks`, `linkages`, `js`, `css`, `toList`, `blocks`, `desc`, `status`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'delete', 'delete', '删除原始需求', 'single', 'different', 'none', 'none', 'browseandview', 'normal', 'direct', 0, 1, 'buildin', 0, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'enable', 'rnd', 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowaction`(`module`, `action`, `method`, `name`, `type`, `batchMode`, `extensionType`, `open`, `position`, `layout`, `show`, `order`, `buildin`, `role`, `virtual`, `conditions`, `verifications`, `hooks`, `linkages`, `js`, `css`, `toList`, `blocks`, `desc`, `status`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'close', 'operate', '关闭原始需求', 'single', 'different', 'none', 'modal', 'browseandview', 'normal', 'direct', 0, 1, 'buildin', 0, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'enable', 'rnd', 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowaction`(`module`, `action`, `method`, `name`, `type`, `batchMode`, `extensionType`, `open`, `position`, `layout`, `show`, `order`, `buildin`, `role`, `virtual`, `conditions`, `verifications`, `hooks`, `linkages`, `js`, `css`, `toList`, `blocks`, `desc`, `status`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'review', 'review', '评审原始需求', 'single', 'different', 'none', 'normal', 'browseandview', 'normal', 'direct', 0, 1, 'buildin', 0, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'enable', 'rnd', 'admin', '2024-05-12 17:38:28', '', NULL);
INSERT INTO `zt_workflowaction`(`module`, `action`, `method`, `name`, `type`, `batchMode`, `extensionType`, `open`, `position`, `layout`, `show`, `order`, `buildin`, `role`, `virtual`, `conditions`, `verifications`, `hooks`, `linkages`, `js`, `css`, `toList`, `blocks`, `desc`, `status`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'view', 'view', '原始需求详情', 'single', 'different', 'extend', 'normal', 'browseandview', 'normal', 'direct', 0, 1, 'buildin', 0, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'enable', 'rnd', 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowaction`(`module`, `action`, `method`, `name`, `type`, `batchMode`, `extensionType`, `open`, `position`, `layout`, `show`, `order`, `buildin`, `role`, `virtual`, `conditions`, `verifications`, `hooks`, `linkages`, `js`, `css`, `toList`, `blocks`, `desc`, `status`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'exporttemplate', 'exporttemplate', '导出模板', 'single', 'different', 'extend', 'normal', 'browseandview', 'normal', 'direct', 0, 1, 'buildin', 0, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'enable', 'rnd', 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowaction`(`module`, `action`, `method`, `name`, `type`, `batchMode`, `extensionType`, `open`, `position`, `layout`, `show`, `order`, `buildin`, `role`, `virtual`, `conditions`, `verifications`, `hooks`, `linkages`, `js`, `css`, `toList`, `blocks`, `desc`, `status`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'export', 'export', '导出数据', 'single', 'different', 'extend', 'normal', 'browseandview', 'normal', 'direct', 0, 1, 'buildin', 0, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'enable', 'rnd', 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowaction`(`module`, `action`, `method`, `name`, `type`, `batchMode`, `extensionType`, `open`, `position`, `layout`, `show`, `order`, `buildin`, `role`, `virtual`, `conditions`, `verifications`, `hooks`, `linkages`, `js`, `css`, `toList`, `blocks`, `desc`, `status`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'import', 'import', '导入', 'single', 'different', 'extend', 'normal', 'browseandview', 'normal', 'direct', 0, 1, 'buildin', 0, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'enable', 'rnd', 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowaction`(`module`, `action`, `method`, `name`, `type`, `batchMode`, `extensionType`, `open`, `position`, `layout`, `show`, `order`, `buildin`, `role`, `virtual`, `conditions`, `verifications`, `hooks`, `linkages`, `js`, `css`, `toList`, `blocks`, `desc`, `status`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'showimport', 'showimport', '导入数据展示', 'single', 'different', 'extend', 'normal', 'browseandview', 'normal', 'direct', 0, 1, 'buildin', 0, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'enable', 'rnd', 'admin', '2024-06-18 09:00:00', '', NULL);

INSERT INTO `zt_workflowdatasource`(`type`, `name`, `code`, `datasource`, `view`, `keyField`, `valueField`, `buildin`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('lang', '需求池状态', 'demandpoolStatus', 'demandpoolStatus', '', '', '', 1, 'rnd', 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowdatasource`(`type`, `name`, `code`, `datasource`, `view`, `keyField`, `valueField`, `buildin`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('lang', '原始需求类别', 'demandCategory', 'demandCategory', '', '', '', 1, 'rnd', 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowdatasource`(`type`, `name`, `code`, `datasource`, `view`, `keyField`, `valueField`, `buildin`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('lang', '原始需求来源', 'demandSource', 'demandSource', '', '', '', 1, 'rnd', 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowdatasource`(`type`, `name`, `code`, `datasource`, `view`, `keyField`, `valueField`, `buildin`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('lang', '原始需求状态', 'demandStatus', 'demandStatus', '', '', '', 1, 'rnd', 'admin', '2024-06-20 11:54:04', '', NULL);
INSERT INTO `zt_workflowdatasource`(`type`, `name`, `code`, `datasource`, `view`, `keyField`, `valueField`, `buildin`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('system', '用户为项目负责人项目', 'PMProject', '{\"app\":\"system\",\"module\":\"project\",\"method\":\"getPairsByPM\",\"methodDesc\":\"Get project pairs by PM.\",\"params\":[]}', '', '0', '0', 1, 'rnd', 'admin', '2024-06-20 18:37:37', '', NULL);
INSERT INTO `zt_workflowdatasource`(`type`, `name`, `code`, `datasource`, `view`, `keyField`, `valueField`, `buildin`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('lang', '原始需求所属阶段', 'demandStage', 'demandStage', '', '0', '0', 1, 'rnd', 'admin', '2024-06-21 00:12:22', '', NULL);

INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demandpool', 'id', 'mediumint', '8', '需求池编号', 'input', NULL, '', '', '', '', 1, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demandpool', 'dept', 'mediumint', '8', '部门名称', 'select', NULL, 'dept', '', '', '', 2, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demandpool', 'name', 'varchar', '255', '需求池名称', 'input', NULL, '', '', '', '', 3, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demandpool', 'desc', 'text', '', '需求池描述', 'richtext', NULL, '', '', '', '', 4, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demandpool', 'status', 'varchar', '30', '需求池状态', 'select', NULL, (select `id` from `zt_workflowdatasource` where `name` = '需求池状态' and `buildin` = 1 order by id desc limit 1), 'normal', '', '', 5, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demandpool', 'createdBy', 'varchar', '30', '由谁创建', 'select', NULL, '8', '', '', '', 6, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demandpool', 'createdDate', 'datetime', '', '创建日期', 'datetime', NULL, '', '', '', '', 7, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demandpool', 'owner', 'varchar', '30', '需求池负责人', 'select', NULL, '8', '', '', '', 9, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demandpool', 'participant', 'text', '', '需求池参与人', 'multi-select', NULL, '8', '', '', '', 10, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demandpool', 'acl', 'enum', '', '访问控制', 'radio', NULL, '15', 'open', '', '', 11, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demandpool', 'deleted', 'enum', '', '已删除', 'radio', NULL, '[\"\\u672a\\u5220\\u9664\",\"\\u5df2\\u5220\\u9664\"]', '0', '', '', 12, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);

INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'id', 'mediumint', '8', '原始需求编号', 'input', NULL, '', '', '', '', 1, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'pool', 'mediumint', '8', '所属需求池', 'select', NULL, 'sql', '0', '', '', 2, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'module', 'mediumint', '8', '所属模块', 'select', NULL, '11', '0', '', '', 3, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'pri', 'tinyint', '3', '优先级', 'select', NULL, '21', '', '', '', 4, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`( `module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'severity', 'tinyint', '4', '严重程度', 'select', NULL, '24', '', '', '', 5, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`( `module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'category', 'varchar', '30', '原始需求类别', 'select', NULL, (select `id` from `zt_workflowdatasource` where `name` = '原始需求类别' and `buildin` = 1 order by id desc limit 1), '', '', '', 6, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`( `module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'source', 'varchar', '30', '原始需求来源', 'select', NULL, (select `id` from `zt_workflowdatasource` where `name` = '原始需求来源' and `buildin` = 1 order by id desc limit 1), '', '', '', 7, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'sourceNote', 'varchar', '255', '来源备注', 'input', NULL, '', '', '', '', 8, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'name', 'varchar', '255', '原始需求名称', 'input', NULL, '', '', '', '', 9, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'desc', 'text', '', '原始需求描述', 'richtext', NULL, '', '', '', '', 10, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'feedbackBy', 'varchar', '255', '反馈者', 'input', NULL, '', '', '', '', 11, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'email', 'varchar', '255', '反馈邮箱', 'input', NULL, '', '', '4', '', 12, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'mobile', 'varchar', '255', '手机', 'input', NULL, '', '', '6', '', 13, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'assignedTo', 'varchar', '30', '指派给', 'select', NULL, '8', '', '', '', 14, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'reviewer', 'varchar', '30', '评审人', 'select', NULL, '8', '', '', '', 15, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`( `module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'status', 'varchar', '30', '原始需求状态', 'select', NULL, (select `id` from `zt_workflowdatasource` where `name` = '原始需求状态' and `buildin` = 1 order by id desc limit 1), '', '', '', 16, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'deadline', 'datetime', '', '期望完成时间', 'datetime', NULL, '', '', '', '', 17, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'createdBy', 'varchar', '30', '由谁创建', 'select', NULL, '8', '', '', '', 18, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'createdDate', 'datetime', '', '创建日期', 'datetime', NULL, '', '', '', '', 19, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'mailto', 'text', '', '通知人', 'multi-select', NULL, '8', '', '', '', 20, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'deleted', 'enum', '', '已删除', 'radio', NULL, '[\"\\u672a\\u5220\\u9664\",\"\\u5df2\\u5220\\u9664\"]', '0', '', '', 21, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'businessDesc', 'text', '', '业务现状', 'richtext', NULL, '', '', '', '', 21, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'businessObjective', 'text', '', '期望达成的业务效果', 'richtext', NULL, '', '', '', '', 22, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'project', 'mediumint', '8', '归属项目', 'select', NULL, (select `id` from `zt_workflowdatasource` where `name` = '用户为项目负责人项目' and `buildin` = 1 order by id desc limit 1), '0', '', '', 23, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'dept', 'mediumint', '8', '干系部门', 'select', NULL, 'dept', '0', '', '', 24, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'stage', 'varchar', '30', '所属阶段', 'select', NULL, (select `id` from `zt_workflowdatasource` where `name` = '原始需求所属阶段' and `buildin` = 1 order by id desc limit 1), '0', '', '', 25, 0, 0, '0', '0', '0', '1', 1, 'buildin', NULL, 'admin', '2024-06-18 09:00:00', '', NULL);
INSERT INTO `zt_workflowfield`(`module`, `field`, `type`, `length`, `name`, `control`, `expression`, `options`, `default`, `rules`, `placeholder`, `order`, `searchOrder`, `exportOrder`, `canExport`, `canSearch`, `isValue`, `readonly`, `buildin`, `role`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('demand', 'businessUnit', 'text', '', '业务单元', 'multi-select', '', '{\"key\":\"\\u6d4b\\u8bd5\\u6570\\u636e\"}', '', '', '', 0, 0, 0, '0', '0', '0', '0', 0, 'custom', NULL, 'admin', '2024-06-20 12:38:05', '', NULL);

INSERT INTO `zt_workflowlayout`(`module`, `action`, `field`, `order`, `width`, `position`, `readonly`, `mobileShow`, `summary`, `defaultValue`, `layoutRules`, `vision`) VALUES ('demand', 'create', 'businessUnit', 1, '0', '', '0', '0', '', '', '', 'rnd');
INSERT INTO `zt_workflowlayout`(`module`, `action`, `field`, `order`, `width`, `position`, `readonly`, `mobileShow`, `summary`, `defaultValue`, `layoutRules`, `vision`) VALUES ('demand', 'edit', 'businessUnit', 1, '0', '', '0', '0', '', '', '', 'rnd');
INSERT INTO `zt_workflowlayout`(`module`, `action`, `field`, `order`, `width`, `position`, `readonly`, `mobileShow`, `summary`, `defaultValue`, `layoutRules`, `vision`) VALUES ('demand', 'view', 'businessUnit', 1, '0', '', '0', '0', '', '', '', 'rnd');
INSERT INTO `zt_workflowlayout`(`module`, `action`, `field`, `order`, `width`, `position`, `readonly`, `mobileShow`, `summary`, `defaultValue`, `layoutRules`, `vision`) VALUES ('demand', 'batchcreate', 'businessUnit', 1, '0', '', '0', '0', '', '', '', 'rnd');
INSERT INTO `zt_workflowlayout`(`module`, `action`, `field`, `order`, `width`, `position`, `readonly`, `mobileShow`, `summary`, `defaultValue`, `layoutRules`, `vision`) VALUES ('demand', 'exporttemplate', 'businessUnit', 1, '0', '', '0', '0', '', '', '', 'rnd');
INSERT INTO `zt_workflowlayout`(`module`, `action`, `field`, `order`, `width`, `position`, `readonly`, `mobileShow`, `summary`, `defaultValue`, `layoutRules`, `vision`) VALUES ('demand', 'export', 'businessUnit', 1, '0', '', '0', '0', '', '', '', 'rnd');
INSERT INTO `zt_workflowlayout`(`module`, `action`, `field`, `order`, `width`, `position`, `readonly`, `mobileShow`, `summary`, `defaultValue`, `layoutRules`, `vision`) VALUES ('demand', 'import', 'businessUnit', 1, '0', '', '0', '0', '', '', '', 'rnd');
INSERT INTO `zt_workflowlayout`(`module`, `action`, `field`, `order`, `width`, `position`, `readonly`, `mobileShow`, `summary`, `defaultValue`, `layoutRules`, `vision`) VALUES ('demand', 'showimport', 'businessUnit', 1, '0', '', '0', '0', '', '', '', 'rnd');

alter table `zt_demand` modify dept varchar(255) not null default '';
update `zt_workflowfield` set `type` = 'varchar', `length` = '255', `control` = 'multi-select', `options` = (select `id` from `zt_workflowdatasource` where `code` = 'gradeDeptMenu') where `module` = 'demand' and `field` = 'dept';

INSERT INTO `zt_workflowdatasource`(`type`, `name`, `code`, `datasource`, `view`, `keyField`, `valueField`, `buildin`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('system', '层级部门', 'deptMenu', '{\"app\":\"system\",\"module\":\"dept\",\"method\":\"getOptionMenu\",\"methodDesc\":\"Get option menu of departments.\",\"params\":[]}', '', '0', '0', 1, 'rnd', 'admin', '2024-06-30 09:00:00', '', NULL);
INSERT INTO `zt_workflowdatasource`(`type`, `name`, `code`, `datasource`, `view`, `keyField`, `valueField`, `buildin`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('system', '三级部门', 'gradeDeptMenu', '{\"app\":\"system\",\"module\":\"dept\",\"method\":\"getOptionMenuByGrade\",\"methodDesc\":\"Get option menu of departments by grade.\",\"params\":[{\"name\":\"rootDeptID\",\"type\":\"int\",\"desc\":\"\",\"value\":\"\"},{\"name\":\"grade\",\"type\":\"int\",\"desc\":\"\",\"value\":\"3\"}]}', '', '0', '0', 1, 'rnd', 'admin', '2024-06-30 09:00:00', '', NULL);
