INSERT INTO `zt_workflowdatasource`(`type`, `name`, `code`, `datasource`, `view`, `keyField`, `valueField`, `buildin`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('system', '业务需求归属项目', 'businessProject', '{\"app\":\"system\",\"module\":\"demand\",\"method\":\"getBusinessProject\",\"methodDesc\":\"Get business project by projectapproval.\",\"params\":[]}', '', '0', '0', 1, 'rnd', 'admin', '2024-08-05 09:00:00', '', NULL);

ALTER TABLE `zt_project` ADD `instance` int(8) NOT NULL DEFAULT '0';

update `zt_workflowfield` set `type` = 'varchar', `length` = '255', `options` = '{"1":"\\u7d27\\u6025","2":"\\u4e2d\\u7b49","3":"\\u4e00\\u822c","4":"\\u4e0d\\u91cd\\u8981"}', `readonly` = '0', `buildin` = '0', `role` = 'custom', `order` = '0', `rules` = '1', `name` = '业务重要程度' where `module` = 'demand' and `field` = 'severity';

INSERT INTO `zt_workflowlayout`(`module`, `action`, `field`, `order`, `width`, `position`, `readonly`, `mobileShow`, `summary`, `defaultValue`, `layoutRules`, `vision`, `colspan`, `titleWidth`, `titleColspan`) VALUES ('demand', 'view', 'severity', 2, '0', '', '0', '0', '', '', '', 'rnd', 1, 'auto', 1);
INSERT INTO `zt_workflowlayout`(`module`, `action`, `field`, `order`, `width`, `position`, `readonly`, `mobileShow`, `summary`, `defaultValue`, `layoutRules`, `vision`, `colspan`, `titleWidth`, `titleColspan`) VALUES ('demand', 'batchcreate', 'severity', 2, '0', '', '0', '0', '', '', '', 'rnd', 1, 'auto', 1);
INSERT INTO `zt_workflowlayout`(`module`, `action`, `field`, `order`, `width`, `position`, `readonly`, `mobileShow`, `summary`, `defaultValue`, `layoutRules`, `vision`, `colspan`, `titleWidth`, `titleColspan`) VALUES ('demand', 'exporttemplate', 'severity', 2, '0', '', '0', '0', '', '', '', 'rnd', 1, 'auto', 1);
INSERT INTO `zt_workflowlayout`(`module`, `action`, `field`, `order`, `width`, `position`, `readonly`, `mobileShow`, `summary`, `defaultValue`, `layoutRules`, `vision`, `colspan`, `titleWidth`, `titleColspan`) VALUES ('demand', 'export', 'severity', 2, '0', '', '0', '0', '', '', '', 'rnd', 1, 'auto', 1);
INSERT INTO `zt_workflowlayout`(`module`, `action`, `field`, `order`, `width`, `position`, `readonly`, `mobileShow`, `summary`, `defaultValue`, `layoutRules`, `vision`, `colspan`, `titleWidth`, `titleColspan`) VALUES ('demand', 'import', 'severity', 2, '0', '', '0', '0', '', '', '', 'rnd', 1, 'auto', 1);
INSERT INTO `zt_workflowlayout`(`module`, `action`, `field`, `order`, `width`, `position`, `readonly`, `mobileShow`, `summary`, `defaultValue`, `layoutRules`, `vision`, `colspan`, `titleWidth`, `titleColspan`) VALUES ('demand', 'showimport', 'severity', 2, '0', '', '0', '0', '', '', '', 'rnd', 1, 'auto', 1);
INSERT INTO `zt_workflowlayout`(`module`, `action`, `field`, `order`, `width`, `position`, `readonly`, `mobileShow`, `summary`, `defaultValue`, `layoutRules`, `vision`, `colspan`, `titleWidth`, `titleColspan`) VALUES ('demand', 'create', 'severity', 2, '0', '', '0', '0', '', '', '', 'rnd', 1, 'auto', 1);
INSERT INTO `zt_workflowlayout`(`module`, `action`, `field`, `order`, `width`, `position`, `readonly`, `mobileShow`, `summary`, `defaultValue`, `layoutRules`, `vision`, `colspan`, `titleWidth`, `titleColspan`) VALUES ('demand', 'edit', 'severity', 2, '0', '', '0', '0', '', '', '', 'rnd', 1, 'auto', 1);

INSERT INTO `zt_workflowdatasource`(`type`, `name`, `code`, `datasource`, `view`, `keyField`, `valueField`, `buildin`, `vision`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES ('system', '项目管理业务需求', 'projectapprovalBusiness', '{\"app\":\"system\",\"module\":\"projectapproval\",\"method\":\"getProjectapprovalBusiness\",\"methodDesc\":\"Get business menu for projectapproval\",\"params\":[]}', '', '0', '0', 1, 'rnd', 'admin', '2024-08-07 16:13:01', '', NULL);