CREATE TABLE `zt_copyflow_business` (
  `id` mediumint unsigned NOT NULL AUTO_INCREMENT,
  `mailto` text NOT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'projectchange',
  `severity` varchar(255) NOT NULL,
  `createdDept` varchar(255) NOT NULL,
  `deadline` date NOT NULL,
  `reasonType` varchar(255) NOT NULL,
  `desc` text NOT NULL,
  `name` varchar(255) NOT NULL,
  `demand` text NOT NULL,
  `dept` text NOT NULL,
  `businessDesc` text NOT NULL,
  `businessObjective` text NOT NULL,
  `project` varchar(255) DEFAULT NULL COMMENT '项目',
  `developmentBudget` varchar(255) NOT NULL,
  `outsourcingBudget` varchar(255) NOT NULL,
  `processChange` varchar(255) NOT NULL DEFAULT '2',
  `processName` varchar(255) NOT NULL,
  `businessUnit` varchar(255) NOT NULL,
  `business` int(8) NOT NULL,
  `version` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
